# Generated by Django 4.1.3 on 2022-12-09 21:55

from django.db import migrations, models
from django.utils import timezone

from backend.beyondmd.models import Reviewer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('muscle', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('instructions', models.TextField()),
                ('reviewer', models.ForeignKey(Reviewer))
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=(
                    (1, '1 star'),
                    (2, '2 stars'),
                    (3, '3 stars'),
                    (4, '4 stars'),
                    (5, '5 stars'),
                ))),
                ('comment', models.CharField()),
                ('posted', models.DateTimeField(default=timezone.now)),
            ],
        ),
    ]
