# Generated by Django 4.1.3 on 2022-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('muscle', models.CharField(max_length=30)),
                ('difficulty', models.CharField(max_length=10)),
                ('instructions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[('ONE_RATING', 1), ('TWO_RATING', 2), ('THREE_RATING', 3), ('FOUR_RATING', 4), ('FIVE_RATING', 5)])),
                ('comment', models.CharField(max_length=50)),
                ('posted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
