# Generated by Django 4.1.4 on 2022-12-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyondmd', '0003_rename_exercise_reviewer_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
