# Generated by Django 4.1.4 on 2022-12-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyondmd', '0004_rename_exercise_id_reviewer_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
