# Generated by Django 4.1.4 on 2022-12-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyondmd', '0005_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
