# Generated by Django 4.1.4 on 2022-12-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyondmd', '0007_alter_exercise_id_alter_reviewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
